name: yaml-schema-checker
description: A Github action for validating .yaml files using JSON schemas
branding:
  icon: check-square
  color: blue
inputs:
  jsonSchemaFile:
    description: A JSON schema file following the format used at https://www.schemastore.org
    required: true
  yamlFiles:
    description: A list of files, directories, and wildcard patterns to be validated
    required: true
  filesSeparator:
    description: "Separator used to split the files input"
    default: ","
    required: false
  enableGithubStepSummary:
    description: "Enable writing the output to the GitHub step summary for easier viewing"
    default: false
    required: false
  stripContentFromPath:
    description: "Remove the provided string from any path outputs (useful for shortening long paths in the log and summary)"
    default: ""
    required: false
outputs:
  validFiles:
    description: Comma separated list of files that passed
  invalidFiles:
    description: Comma separated list of files that failed
runs:
  using: "node16"
  main: "dist/index.js"
